server:
  port: 2003
spring:
  application:
    name: seata-storage
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.17.128:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

seata:
  registry:
    nacos:
      server-addr: 192.168.17.128:8848
      namespace: 515feab8-9cbd-4819-87a9-9d4ada6c575d
      group: seata_group
      application: seata-server
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
